name: ESG Daily Dataset
on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch prices
        run: python fetch_prices.py

      - name: Fetch ESG news (GDELT)
        run: python fetch_esg_news_gdelt.py

      - name: Build latest datasets
        run: python make_dataset.py

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/*
          git commit -m "Auto-update ESG datasets $(date -u +'%Y-%m-%d')" || echo "No changes"
          git push
