name: Daily ESG Dataset Update

on:
  schedule:
    - cron: "0 9 * * *"   
  workflow_dispatch:       

permissions:
  contents: write  

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: data-science-projects-starter/data-science-projects/esg-stock-event-study

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data pipeline
        run: |
          python fetch_prices.py
          python fetch_esg_news_gdelt.py
          python make_dataset.py

      - name: Commit & push results
        working-directory: ${{ github.workspace }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data-science-projects-starter/data-science-projects/esg-stock-event-study/data/*
          git commit -m "Daily ESG dataset update" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push


